services:
  app:
    image: todo-front-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173

  backend:
    image: todo-back-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend/:/app
    ports:
      - 3000:3000
    environment: 
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-back-prod
  
  debug-helper:
    image: busybox

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./todo-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

  redis:
    image: redis
    container_name: todo-redis
    volumes:
      - ./todo-backend/redis_data/:/data
    command:
      ["redis-server", "--appendonly", "yes"]

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy